### PR TITLE
Rename :focus-ring to :focus-visible

### PR DESCRIPTION
**Pull request by alice**
@robdodson PTAL - will wait for https://github.com/w3c/csswg-drafts/pull/2104 to go in obviously.

Also, after this will need to do a major release and rename the repo and NPM module.

### CODE REVIEW

**Comment by robdodson** [comment]
I think it might be useful for the README to have a note somewhere that this was originally called `:focus-ring` but renamed to `:focus-visible`. We've already done a fair amount of devrelling telling folks about :focus-ring so anything we can do to migrate people's thoughts will be useful.

**Comment by robdodson** [comment]
oh hm... we're also going to need to npm deprecate wicg-focus-ring and publish a new project, wicg-focus-visible.

Also, these projects would need to update:
- [focus-ring-polyfill](https://www.npmjs.com/package/focus-ring-polyfill)
- [postcss-focus-ring](https://github.com/jonathantneal/postcss-focus-ring)

Possibly others...?

**Comment by robdodson** [comment]
Sorry I see that you commented that we need to rename the repo and npm module. I don't think you can actually rename an npm dependency. You have to deprecate it which logs a warning when people install, then you have to publish a different one.

**Comment by ryuran** [comment]
@robdodson you're right. Rename the npm package is not possible but we can deprecate it and register this new version with a new name.

**Comment by joe-watkins** [comment]
FF team in the know on this? `moz-focusring` https://caniuse.com/#search=focus-ring

**Comment by robdodson** [comment]
@joe-watkins yeah we've spoken with them about this.

**Comment by robdodson** [comment]
oh sorry! you mean are they aware of the name change (I thought you were asking if they're aware that this WICG repo exists). That's actually a good question, I'll ping them to make sure they've seen it.

**Comment by robdodson** [comment]
Also I'm going to see about renaming this polyfill at the end of this week, hopefully rolling it out Friday or even Saturday so we don't break anyone and we have some space to deal with all the npm stuff.

**Pull request merged**
